//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeBlogFitness.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeBlogFitness.Languages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что вы хотите сделать?.
        /// </summary>
        internal static string ActionSelection {
            get {
                return ResourceManager.GetString("ActionSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите название упражнения: .
        /// </summary>
        internal static string ActivityName_Input {
            get {
                return ResourceManager.GetString("ActivityName_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to дату вашего рождения.
        /// </summary>
        internal static string Birthday_User {
            get {
                return ResourceManager.GetString("Birthday_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to калорийность пищи.
        /// </summary>
        internal static string Calories {
            get {
                return ResourceManager.GetString("Calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to количество углеводов.
        /// </summary>
        internal static string Carbs {
            get {
                return ResourceManager.GetString("Carbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A - ввести упражнение.
        /// </summary>
        internal static string Choise_A {
            get {
                return ResourceManager.GetString("Choise_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E - ввести прием пищи.
        /// </summary>
        internal static string Choise_E {
            get {
                return ResourceManager.GetString("Choise_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q - выход.
        /// </summary>
        internal static string Choise_Q {
            get {
                return ResourceManager.GetString("Choise_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to количество жиров.
        /// </summary>
        internal static string Fats {
            get {
                return ResourceManager.GetString("Fats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to время конца упражнения.
        /// </summary>
        internal static string FinishTime {
            get {
                return ResourceManager.GetString("FinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите название еды: .
        /// </summary>
        internal static string FoodName_Input {
            get {
                return ResourceManager.GetString("FoodName_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать в приложение CodeBlogFitness.
        /// </summary>
        internal static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ваш рост.
        /// </summary>
        internal static string Height_User {
            get {
                return ResourceManager.GetString("Height_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение не раcсчитано на людей такого возраста.
        /// </summary>
        internal static string Incorrect_Age {
            get {
                return ResourceManager.GetString("Incorrect_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат даты!.
        /// </summary>
        internal static string Incorrect_DateFormat {
            get {
                return ResourceManager.GetString("Incorrect_DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат поля!.
        /// </summary>
        internal static string Incorrect_FieldFormat {
            get {
                return ResourceManager.GetString("Incorrect_FieldFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to количество белков.
        /// </summary>
        internal static string Proteins {
            get {
                return ResourceManager.GetString("Proteins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to время начала упражнения.
        /// </summary>
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите ваш пол: .
        /// </summary>
        internal static string UserGender_Input {
            get {
                return ResourceManager.GetString("UserGender_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите ваше имя: .
        /// </summary>
        internal static string UserName_Input {
            get {
                return ResourceManager.GetString("UserName_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вес порции.
        /// </summary>
        internal static string Weight_Serving {
            get {
                return ResourceManager.GetString("Weight_Serving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ваш вес.
        /// </summary>
        internal static string Weight_User {
            get {
                return ResourceManager.GetString("Weight_User", resourceCulture);
            }
        }
    }
}
