//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeBlogFitness.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages_en_us {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_en_us() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeBlogFitness.Languages.Messages.en_us", typeof(Messages_en_us).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to do?.
        /// </summary>
        internal static string ActionSelection {
            get {
                return ResourceManager.GetString("ActionSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the exercise:.
        /// </summary>
        internal static string ActivityName_Input {
            get {
                return ResourceManager.GetString("ActivityName_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your date of birth.
        /// </summary>
        internal static string Birthday_User {
            get {
                return ResourceManager.GetString("Birthday_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calorie content of food.
        /// </summary>
        internal static string Calories {
            get {
                return ResourceManager.GetString("Calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amount of carbohydrates.
        /// </summary>
        internal static string Carbs {
            get {
                return ResourceManager.GetString("Carbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A - enter exercise.
        /// </summary>
        internal static string Choise_A {
            get {
                return ResourceManager.GetString("Choise_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E - enter food intake.
        /// </summary>
        internal static string Choise_E {
            get {
                return ResourceManager.GetString("Choise_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q - exit.
        /// </summary>
        internal static string Choise_Q {
            get {
                return ResourceManager.GetString("Choise_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amount of fat.
        /// </summary>
        internal static string Fats {
            get {
                return ResourceManager.GetString("Fats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end time of exercise.
        /// </summary>
        internal static string FinishTime {
            get {
                return ResourceManager.GetString("FinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the food:.
        /// </summary>
        internal static string FoodName_Input {
            get {
                return ResourceManager.GetString("FoodName_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the CodeBlogFitness app.
        /// </summary>
        internal static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your height.
        /// </summary>
        internal static string Height_User {
            get {
                return ResourceManager.GetString("Height_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is not designed for people of this age.
        /// </summary>
        internal static string Incorrect_Age {
            get {
                return ResourceManager.GetString("Incorrect_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date format!.
        /// </summary>
        internal static string Incorrect_DateFormat {
            get {
                return ResourceManager.GetString("Incorrect_DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field format!.
        /// </summary>
        internal static string Incorrect_FieldFormat {
            get {
                return ResourceManager.GetString("Incorrect_FieldFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amount of proteins.
        /// </summary>
        internal static string Proteins {
            get {
                return ResourceManager.GetString("Proteins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exercise start time.
        /// </summary>
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your gender:.
        /// </summary>
        internal static string UserGender_Input {
            get {
                return ResourceManager.GetString("UserGender_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name:.
        /// </summary>
        internal static string UserName_Input {
            get {
                return ResourceManager.GetString("UserName_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serving weight.
        /// </summary>
        internal static string Weight_Serving {
            get {
                return ResourceManager.GetString("Weight_Serving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your weight.
        /// </summary>
        internal static string Weight_User {
            get {
                return ResourceManager.GetString("Weight_User", resourceCulture);
            }
        }
    }
}
